name: Unit Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: true

      # Set up a matrix to run the following 10 configurations:
      # 1. <Windows, Release, latest MSVC compiler toolchain on the default runner image, default generator>
      # 1. <Windows, Debug, latest MSVC compiler toolchain on the default runner image, default generator>
      matrix:
        build_type: [Debug, Release]

    steps:
      - uses: actions/checkout@v5

      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Enable MSVC Developer Command Prompt
        uses: TheMrMilchmann/setup-msvc-dev@v4
        with:
          arch: x64

      - name: Configure CMake
        run: >
          cmake -B ${{ steps.strings.outputs.build-output-dir }}
          -G Ninja
          -DCMAKE_CXX_COMPILER=${cl}
          -DCMAKE_C_COMPILER=${cl}
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -D ENABLE_STRICT=ON
          -D NONCOMPREHENSIVE=ON
          -DSDL_UNIX_CONSOLE_BUILD=ON
          -S ${{ github.workspace }}

      - name: Build
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

      - name: Test
        working-directory: ${{ steps.strings.outputs.build-output-dir }}
        run: ctest --build-config ${{ matrix.build_type }} -j 4 --output-on-failure